entered_sentence = input()
worlds = entered_sentence.split()
variable_1 = worlds[0].capitalize()
variable_2 = worlds[1].upper()
new_file = open("Less_4.txt", "w")
print(entered_sentence, end="<<<>>>", file=new_file)
print("!%(var_2)s %(var_1)s?" % {"var_2": variable_2, "var_1": variable_1}, end="<<<>>>", file=new_file)
print("!{} {}?".format(variable_2, variable_1), end="<<<>>>", file=new_file)
print(f"!{variable_2} {variable_1}?", file=new_file)
new_file.close()
